{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "fintrack.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "fintrack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        {{- include "fintrack.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101          # nginx-unprivileged
        runAsGroup: 101
      containers:
        - name: frontend
          image: {{ include "fintrack.image" (dict "name" "frontend" "root" $) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet: { path: /, port: http }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            periodSeconds: 15
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false   # nginx writes its cache/pid under /tmp,/var
            capabilities: { drop: ["ALL"] }
{{- end }}
