# Secret Manager holds every runtime secret; the app reads them via its GSA
# (Secret Manager CSI driver / External Secrets — see the runbook).

# DB password — generated by Terraform, never printed or committed.
resource "google_secret_manager_secret" "db_password" {
  secret_id = "fintrack-db-password"
  replication {
    auto {}
  }
  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db.result
}

# Anthropic API key — created empty; add a version out-of-band to enable AI:
#   gcloud secrets versions add fintrack-anthropic-api-key --data-file=-
resource "google_secret_manager_secret" "anthropic" {
  secret_id = "fintrack-anthropic-api-key"
  replication {
    auto {}
  }
  depends_on = [google_project_service.enabled]
}

# JWT signing key (PKCS#8 PEM) — created empty; add the PEM as a version:
#   gcloud secrets versions add fintrack-jwt-signing-key --data-file=jwt-signing.pem
resource "google_secret_manager_secret" "jwt_key" {
  secret_id = "fintrack-jwt-signing-key"
  replication {
    auto {}
  }
  depends_on = [google_project_service.enabled]
}
